name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write  # allows pushing to the output branch

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contributions Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: abhi-nav-25
          outputs: |
            dist/github-snake.svg?color_snake=#00bfff
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#00bfff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update blue snake animation [skip ci]"

